# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1409119988);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131030081914");
user_pref("browser.slowStartup.averageTime", 2367);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20131030081914");
user_pref("browser.startup.homepage_override.mstone", "25.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1409206268439");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1409119868438");
user_pref("datareporting.sessions.current.activeTicks", 25);
user_pref("datareporting.sessions.current.firstPaint", 2283);
user_pref("datareporting.sessions.current.main", 618);
user_pref("datareporting.sessions.current.sessionRestored", 2374);
user_pref("datareporting.sessions.current.startTime", "1409119867082");
user_pref("datareporting.sessions.current.totalTime", 173);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406851504000,\"rdfTime\":1383165391000}}}]");
user_pref("extensions.lastAppVersion", "25.0");
user_pref("extensions.lastPlatformVersion", "25.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20131030081914");
user_pref("gecko.mstone", "25.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.backup.ftp", "proxy.ssn.net");
user_pref("network.proxy.backup.ftp_port", 8080);
user_pref("network.proxy.backup.socks", "proxy.ssn.net");
user_pref("network.proxy.backup.socks_port", 8080);
user_pref("network.proxy.backup.ssl", "proxy.ssn.net");
user_pref("network.proxy.backup.ssl_port", 8080);
user_pref("network.proxy.ftp", "proxy.ssn.net");
user_pref("network.proxy.ftp_port", 8080);
user_pref("network.proxy.http", "proxy.ssn.net");
user_pref("network.proxy.http_port", 8080);
user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1,*.ssn.net");
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.socks", "proxy.ssn.net");
user_pref("network.proxy.socks_port", 8080);
user_pref("network.proxy.ssl", "proxy.ssn.net");
user_pref("network.proxy.ssl_port", 8080);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1409119867);
user_pref("toolkit.telemetry.previousBuildID", "20131030203622");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1411711871);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
